# Generated by Django 3.0 on 2019-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191224_0937'),
        ('accounts', '0002_account_favorite_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favorite_courses',
            field=models.ManyToManyField(related_name='fav_course_users', to='courses.Course'),
        ),
    ]
