# Generated by Django 3.0 on 2020-05-27 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='manager',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='organization',
            name='employees',
        ),
        migrations.AddField(
            model_name='organization',
            name='employees',
            field=models.ManyToManyField(related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
