# Generated by Django 3.0 on 2019-12-20 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('usr', 'user')], max_length=3)),
                ('min_pass_grade', models.FloatField(verbose_name='minimum pass grade')),
                ('status', models.CharField(choices=[('drf', 'draft'), ('rdy', 'ready')], default='drf', max_length=3)),
                ('type', models.CharField(choices=[('pbl', 'public'), ('prv', 'private'), ('ind', 'individual')], default='pbl', max_length=3)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
