# Generated by Django 3.0 on 2019-12-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191224_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='finished_at',
            field=models.DateField(blank=True),
        ),
    ]
