# Generated by Django 3.0 on 2019-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191224_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='progress',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
