# Generated by Django 3.0 on 2019-12-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20191224_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='current_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Page'),
        ),
    ]
