# Generated by Django 3.0 on 2020-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200109_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('chb', 'checkbox'), ('rad', 'radio')], max_length=3),
        ),
    ]
