# Generated by Django 3.0 on 2020-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200109_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='page',
        ),
        migrations.AddField(
            model_name='results',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
