# Generated by Django 3.0 on 2020-01-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_result_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollment',
            old_name='grade',
            new_name='points',
        ),
    ]
