# Generated by Django 3.0 on 2020-01-16 14:27

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200115_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(default='courses/default.png', upload_to='courses/', validators=[courses.models.validate_image_size]),
        ),
    ]
