# Generated by Django 3.0 on 2020-02-03 18:47

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='_grade',
            field=models.IntegerField(db_column='grade', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(default='courses/default.png', upload_to=courses.models.course_cover_path, validators=[courses.models.validate_image_size]),
        ),
    ]
