# Generated by Django 3.0 on 2020-05-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='certificate',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificateTemplate',
        ),
    ]
